Added sort function
CSIS-iLab/satellite-dashboard pull request #132
Opened 2021-02-28 02:07 UTC by jdromero88

2021-03-01 18:28 UTC, jnschrag requested changes
Really  nice job on this, José! The functionality works great. There's a couple of style things we need to address and then I have some suggestions for refactoring to make this a little bit cleaner:

- The options listed in the sort dropdown are correct, but when you select them, it shows the selected value as opposed to the label. We want the label to be what is selected.

<img width="201" alt="Screen Shot 2021-03-01 at 1 19 00 PM" src="https://user-images.githubusercontent.com/1896496/109541643-073a3080-7a92-11eb-9530-46550d1d9144.png">


- Double check the styles in Figma. In this instance, we want:
  - The Total # of results should be on the same line as the select box (I would use `display: flex` on the `.details-events__totals` div)
  - We can remove the arrow from the dropdown

2021-03-01 18:28 UTC, jnschrag commented on components/visualizer/details-panel/Events.vue
> +    updateCurrentSort(value) {
Can you explain why this is a method? If we're using `v-model` on the dropdown, it will update `currentSort` automatically, and the `filteredEvents` computed property will update automatically as well.

2021-03-01 18:28 UTC, jnschrag commented on components/visualizer/details-panel/Events.vue
> +      if (selected === 'min_distance') {
This should be an `elseif`. I would also recommend setting the sort value to `min_distance_km`, and then updating this so it's `events.sort((a, b) => a[this.currentSort] - b[this.currentSort])`. It's more reusable that way.

2021-03-01 18:28 UTC, jnschrag commented on components/visualizer/details-panel/Events.vue
> +      let selected = this.currentSort
I would recommend against creating another variable and using `this.currentSort` directly.

2021-03-01 19:43 UTC, jdromero88 commented on components/visualizer/details-panel/Events.vue
> +      if (selected === 'min_distance') {
So the reason I did not use the ```else if (condition) { }``` was just because I'm trying to use the coding style of the [line of sight](https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88).

2021-03-01 19:49 UTC, jdromero88 commented on components/visualizer/details-panel/Events.vue
> +    updateCurrentSort(value) {
I used a method because it wasn't updating the ```CloseApproachesList``` component. So my solution was to use a method to update the ```currentSort``` so this way I was like "forcing" the component to update.
After you review I went back to the docs & I found that I could use the ```reduce``` property to achieve the same thing without using any methods. 💯 👍🏽

2021-03-02 15:02 UTC, jnschrag approved these changes
Really nice job!

2021-03-02 15:02 UTC, merged