Closes #148 | Post: Updated Section
CSIS-iLab/satellite-dashboard pull request #152
Opened 2021-05-24 19:31 UTC by jdromero88

Closes #148 
Hi @jnschrag 
You can test the new feature in this link[http://localhost:3000/analysis/mev-1-intelsat-901](http://localhost:3000/analysis/mev-1-intelsat-901)

Also looks like the class ```.entry-content``` should have a ```background-color: #F2F2F2;``` but please correct me if I am wrong?
P.S. Because the background is white I left the Updated Section bg color also white.

2021-05-25 18:35 UTC, jnschrag requested changes
This is looking good, José. A few things:

- Good catch on the background color! Yes, please update it. It doesn't look like that color (#f2f2f2) was included when we created the color variables, so you'll need to add it in `_variables.scss`. I would call it `$color-post-background`. Please use the RGB format to match the other colors.
- Can you test this on a different post, specifically one of the test posts? This one is a real post, and I don't want to have our test content included on it.
- The date should read "Updated [date]" (we're missing the "Updated" text).
- This CSS should be moved to `post-content.scss`, because this is a block in the content, and so technically could be used on other pages, not just posts. You could simplify the CSS class name to `last-updated__[block name]` too (eg. `.last-updated__date`).
- After looking at this in practice, I think the HTML structure is a bit off. Semantically, it doesn't make sense for the date to only be a paragraph. It functionally kind of serves the same role as a heading. I think the HTML should be updated to this:

```html
<div class="wp-block-lazyblock-last-updated-section">
  <hr class="last-updated__separator">
  <div class="last-updated">
    <h2 class="last-updated__date">Updated [Date]</h2>
    [Content ]
  </div>
</div>
```
- Because it's currently set to be a paragraph, the space between the date & the content is off. It should be `1rem`.

2021-05-25 18:35 UTC, jnschrag commented on assets/css/pages/post.scss
> +    @include full-width-background($color-white-100, true);
You shouldn't need to specify this, since it'll inherit the background of the parent post. This means you can also remove the pseudo elements too.

2021-05-25 18:35 UTC, jnschrag commented on assets/css/pages/post.scss
> +      color: rgba(0, 0, 0, 0.2);
When styling horizontal rules, you usually want to style the border property instead, so this would be `1px solid $color-black-120`.

2021-05-25 18:35 UTC, jnschrag commented on assets/css/pages/post.scss
> +      @extend %font-ui-text-sm-oxygen;
I don't think this is the right placeholder. Figma says "post text/sm", which would be `%font-post-text-sm`.

2021-05-26 21:57 UTC, jdromero88 commented
Hey @jnschrag because the Glossary, About pages have a ```background color: #f7f7f7```
& after consulting with Tucker for consistency she advice to use the same color on the Analysis page, so I went ahead & update this file ```_placeholders.scss``` to

```
%page-content-bg {
  color: $color-black-190;
  // background: $color-white-100;
  background: $color-page-background;

  // Ensures that background extends to edges on mobile devices
  @include breakpoint($break: 'medium', $dir: 'max-width') {
    @include full-width-background(
      $background: $color-page-background,
      $includeMargins: true
    );

    &::before,
    &::after {
      z-index: -1;
    }
  }
}
```
I'm not sure if this the right approach but this is what makes sense in my brain. But let me know if is otherwise.

You can test the changes [http://localhost:3000/analysis/hello-world](http://localhost:3000/analysis/hello-world) and [http://localhost:3000/analysis/test-post](http://localhost:3000/analysis/test-post)

2021-05-27 15:31 UTC, jnschrag requested changes
This looks great! Two small changes. One is a variable name I flagged, and the other is miscommunication on my part.

If you look at the HTML for the block in the browser:

<img width="669" alt="Screen Shot 2021-05-27 at 11 29 34 AM" src="https://user-images.githubusercontent.com/1896496/119854312-f8231d00-bede-11eb-9be2-f9c7d1fb9d4b.png">

You can remove the div you added to the lazyblock with the class of `wp-block-lazyblock-last-updated-section`. There's a container div with that class automatically created by the plugin, so you don't need to add it.

2021-05-27 16:58 UTC, jnschrag approved these changes
Perfect, thanks so much, José!

2021-05-27 16:58 UTC, merged