Part 1: Feat/linking to the glossary page
CSIS-iLab/satellite-dashboard pull request #153
Opened 2021-05-27 19:03 UTC by jdromero88

Hi @jnschrag here is the part 1 of the issue Glossary Terms in Analysis Posts # 150.
You can test it [here](http://localhost:3000/analysis/hello-world) and [here](http://localhost:3000/analysis/test-post)

2021-06-01 18:19 UTC, jnschrag requested changes
Thanks, José! This is close, but the anchor links aren't working correctly. On the glossary page, the `slug` of the glossary term is used as the `id`. So for example, if I wanted to link to "Mean Orbital Speed" (which is the term the example in the Test Post is meant to go to), the url should be `/glossary#mean-oribital-speed`.

<img width="451" alt="Screen Shot 2021-06-01 at 2 17 15 PM" src="https://user-images.githubusercontent.com/1896496/120371656-1d9b9680-c2e4-11eb-91c3-03f782436c6d.png">

Right now, the URL uses the Post ID as the anchor identifier, which means it doesn't go to the correct place. Ideally, we'd want to swap it out so it uses the slug instead, so we get a nice URL. But if that isn't possible, then we need to update the glossary page to use the Post ID as the anchor instead of the slug.

2021-06-02 18:57 UTC, jdromero88 commented
Hi @jnschrag sorry, I totaly missed the id on the glossary. Now is updated & is working properly.
You can test it [here](http://localhost:3000/analysis/hello-world) and [here](http://localhost:3000/analysis/test-post)

2021-06-07 18:29 UTC, jnschrag requested changes
Thank you, @jdromero88! This is almost there!

2021-06-07 18:29 UTC, jnschrag commented on store/analysis.js
> +function linkFormatter(contentParsed, content) {
Can we rename this to `glossaryLinkFormatter` so it's more specific on which kinds of links we're formatting?

2021-06-07 18:29 UTC, jnschrag commented on store/analysis.js
> +    const id = link._attrs.href.substring(38, link._attrs.href.length - 1)
While this works, it's also very dependent on the URL structure not changing, which makes me nervous because if we ever change the WPE URL, this would stop working and we'd have to figure out why. A more future-proof solution might be to instead `.split()` the URL on the `/` character to create an array, and then get either the last element in the array or the second to last element in the array depending on if it ends in a `/`. Something like this should get you started:

```
const url = link._attrs.href.split('/') // Creates an array.
const urlLength = url.length
let id = url[urlLength - 1] != '' ? url[urlLength - 1] : url[urlLength - 2] // This should check to see if the last element in the array is our glossary term (or an empty space/ending backslash) and return the correct array value accordingly.
```

This is still not entirely future proof, in that if we ever change the structure of the URL so the glossary term is not last, this would also break. But that's much less likely than us changing the URL & the amount of characters it has that the `substring` method relies on.

2021-06-07 19:42 UTC, jdromero88 commented on store/analysis.js
> +    let id = url[urlLength - 1] != '' ? url[urlLength - 1] : url[urlLength - 2]
hey @jnschrag thank you for opening my brain. this way of using the ternary operator just blows my mind!

2021-06-07 19:56 UTC, jnschrag approved these changes

2021-06-07 19:57 UTC, merged