Update country field information
CSIS-iLab/satellite-dashboard pull request #165
Opened 2021-07-06 17:17 UTC by jdromero88

Hi @jnschrag
Not sure if here `CloseApproachesList.vue` we should show the country but for now I added it. 
![Screenshot at 2021-07-06 13-12-05](https://user-images.githubusercontent.com/51330062/124641146-5cc98400-de5c-11eb-9ca1-4970d2813ad8.png)

2021-07-07 15:10 UTC, jnschrag requested changes
Thanks for looking at this, @jdromero88! This all looks really good. I had one question about a particular line that I left. Besides that, can you go ahead and just remove any references to `countryOfJurisdiction` instead of commenting it out? We're going to full on remove that field from the site, so let's just get rid of it.

2021-07-07 15:10 UTC, jnschrag commented on store/satellites.js
> +  let countryID = value != undefined ? value : 'TBD'
Why was this added?

2021-07-08 12:09 UTC, jdromero88 commented on store/satellites.js
> +  let countryID = value != undefined ? value : 'TBD'
Oh I forgot to remove this, but for testing purposes I was using it in a different way. On line 198 I was passing the whole object sat:
```
let countryOfLaunch = formatCountries(sat)
```

2021-07-08 16:42 UTC, jnschrag requested changes
Hey José, thanks for this. I think I miscommunicated what I wanted. We're _replacing_ `countryOfJurisdiction` with `countryOfLaunch`. We don't just want to eliminate `countryOfJurisdiction`, we need to replace it so any functions/data/etc. that uses that field now uses `countryOfLaunch`. So in a file like `store/satellite.js`, we actually need to keep all of those functions that were removed, but replace it so it uses `countryOfLaunch`. Does that make sense?

2021-07-12 21:02 UTC, jnschrag approved these changes
Note that we still need to update the countries list to work with multiple countries.

2021-07-12 21:02 UTC, merged