Refactor/magic improvements
CSIS-iLab/satellite-dashboard pull request #183
Opened 2021-07-15 17:06 UTC by HP4k1h5

2021-07-15 19:15 UTC, jnschrag requested changes

2021-07-15 19:15 UTC, jnschrag commented on assets/css/components/modal.scss
>    overflow-x: auto;
This can be simplified to `overflow: auto`.

2021-07-15 19:15 UTC, jnschrag commented on components/visualizer/MagicChart.vue
> +    class="magic-chart modal"
We need to modify this a bit. The `.modal` class is being applied to two elements, the containing div and the `role="dialog"` div, which opens this up to conflict with each other. I think we can probably remove `modal` from the `<Modal>` tag, but take a look and let me know what you think.

2021-07-15 19:15 UTC, jnschrag commented on assets/css/components/magic-chart.scss
> +  width: 45vw;
Can we try this instead?
```
width: 100%;
max-width: 680px;
max-height: 85vh;
margin: rem(16);
```

Using `vw` for the width units here causes it to shrink a little oddly as the screen gets smaller.

2021-07-16 18:42 UTC, HP4k1h5 commented on assets/css/components/magic-chart.scss
> +  width: 45vw;
had a tough time getting the right behavior with these. setting a width was shifting the modal all the way left in the screen

2021-07-19 14:57 UTC, jnschrag approved these changes

2021-07-19 15:00 UTC, merged