Feat/itu filings
CSIS-iLab/satellite-dashboard pull request #187
Opened 2021-07-20 20:43 UTC by HP4k1h5

mostly there. below is a screen of the data table. ive applied some css styles, but wanted some guidance on how to handle long "bands" lists, they can be bigger than this, e.g. 
```
C, K, Ka, Ku, L, S, ULF, V, VHF, W, X
```

possible partial solutions include
- reducing font size/weight/width
- allowing horizontal scroll in this table field
- hovering for full info
- stacking these vertically like what we have now

<img width="375" alt="Screen Shot 2021-07-20 at 4 38 27 PM" src="https://user-images.githubusercontent.com/20137484/126392550-6546afe5-d453-4ee0-8b50-2a0159580d1b.png">

2021-07-22 16:15 UTC, jnschrag requested changes
Overall this looks really good. I've got a couple of styling tweaks, but functionally I think this is great.

On your question about how to handle the overflow on the table, I think that's probably a question you should ask Tucker in the #aerospace channel in Slack and see what she says.

- [x] Can we make this section heading, "Nearby ITU Filings"?
- [x] Between the section heading and the table, can we add this microcopy (use the same styles as the "Updated from..." text in the Orbit section). `This list includes ITU filings near [%Longitude].` Where `[%Longitude]` is the longitude we're using to populate the table?
- [x] The column headings for the table should have these styles applied:
```
color: $color-white-160;
@extend %font-ui-text-sm-oxygen;
font-weight: bold;
text-transform: uppercase;
```
- [ ] There should be 16px of padding on the right & left side of the table rows. Right now the longitude number runs up right against the edge (might be impacted based on what Tucker has to say about the size of the table)
- [ ] Can the link icon be centered under the "Link" table heading? Can it also change to `$color-white-100` on hover?

2021-07-22 16:15 UTC, jnschrag commented on assets/css/components/itu-block.scss
> +    .itu-list & {
I don't think the `.itu-list` class is used anywhere in the code base, is it? If so, it can probably be removed.

2021-07-22 20:15 UTC, HP4k1h5 commented
The `external-link` icon has color applied in the svg and this is preventing color changes on hover. we'll have to re-import this svg without coloring applied

2021-07-23 14:55 UTC, jnschrag requested changes
Thanks for fixing this up. Just a few more changes. I pinged Tucker in Slack so hopefully she'll look at this next week.

**Edit:** How do you feel about setting a max height of the ITU filings table, say ~400px, and having there be an internal scroll? Or is that too much scroll within a scrollable area?

2021-07-23 14:55 UTC, jnschrag commented on assets/css/components/itu-block.scss
> +    grid-template-columns: auto;
The `grid-template-columns`, `@include shadow` and hover states can all be removed from this selector. They aren't used here.

2021-07-23 14:55 UTC, jnschrag commented on assets/css/components/itu-block.scss
> +    margin-left: 16px;
Can you switch this to `rem(16)` for consistency? And can we apply it on the `<th>` as well?

2021-07-23 14:55 UTC, jnschrag commented on assets/css/components/itu-block.scss
> +  &__link {
The last column in the table should have the same amount of padding on the outside as the first column does.

2021-07-23 14:55 UTC, jnschrag commented on assets/css/components/itu-block.scss
> +    &svg:hover {
We can update this to so it's applied when we fix the SVG.

```
&__link {
  a {
    color: $color-orangedull-100;

    &:hover {
      color: $color-white-180;
    }
}
```

2021-07-23 14:55 UTC, jnschrag commented on components/visualizer/details-panel/Details.vue
> +    <span class="details-panel__small-desc"
This should be a `<p>` tag. And can we add a `.` at the end of the sentence? Thanks!

2021-07-23 14:55 UTC, jnschrag commented on components/visualizer/details-panel/Details.vue
> +    <div v-else class="details-panel__comments">
This should also probably be a `<p>` tag, and should use a different class, since `.details-panel__comments` is specifically for the comments section. We don't want to cross-contaminate styles accidentally.

2021-07-23 18:37 UTC, jnschrag approved these changes
This looks good to me. I'm going to leave it unmerged for now until @tuckabelle has a chance to look at it next week. Nice job, @HP4k1h5!

2021-08-20 13:25 UTC, merged