edit: fix panel content transition; updates open
CSIS-iLab/satellite-dashboard pull request #204
Opened 2021-08-06 14:25 UTC by HP4k1h5

Close #203
Close #202

2021-08-09 16:32 UTC, jnschrag requested changes
Left a few comments on specific items!

2021-08-09 16:32 UTC, jnschrag commented on static/symbols.svg
> +<symbol id="icon-pin" viewBox="0 0 26 25">
We want to replace the `icon-unpin` instead (the one that is not filled in). The `icon-pin` is the filled in version.

2021-08-09 21:23 UTC, jnschrag approved these changes
The pin change looks good. Do you want to remove the reference to the focus states and one of us can look at that as a part of its own issue? I'm happy to take that on and go through and individually remove them. This is good to go and merge in, but I'll wait until the reference to that issue is removed so we don't accidentally close it/forget about it.

2021-08-09 21:57 UTC, HP4k1h5 commented
> Do you want to remove the reference to the focus states and one of us can look at that as a part of its own issue?

@jnschrag there are still [two removed outlines](assets/css/components/panel--left.scss) in the `panel-left` scss. 

do you want me to restore these as well?

2021-08-10 14:44 UTC, jnschrag commented
> > Do you want to remove the reference to the focus states and one of us can look at that as a part of its own issue?
> 
> @jnschrag there are still [two removed outlines](assets/css/components/panel--left.scss) in the `panel-left` scss.
> 
> do you want me to restore these as well?

Oops, I missed that. Nope, this looks good. There might be others, and we'll have to catch those as we go! Gonna accept and merge this in.

2021-08-10 14:44 UTC, merged